// Survey page dictionary (JP/EN - customer-facing survey and result pages)
export const surveyDict: Record<string, { ja: string; en: string }> = {
  "survey.loading": { ja: "読み込み中...", en: "Loading..." },
  "survey.error": { ja: "エラーが発生しました", en: "An error occurred" },
  "survey.textPlaceholder": { ja: "ご回答を入力してください...", en: "Please enter your answer..." },
  "survey.testMode": { ja: "テストモード — この回答はカウントされません", en: "Test Mode — This response will not be counted" },
  "survey.paused": { ja: "ご回答ありがとうございました。現在、口コミ生成を一時停止しております。ご不便をおかけして申し訳ございません。", en: "Thank you for your response. Review generation is currently paused. We apologize for the inconvenience." },
  "survey.generateFailed": { ja: "口コミの生成に失敗しました。", en: "Failed to generate review." },
  "survey.welcome": { ja: "のアンケートへようこそ！いくつか質問させていただきます。", en: "'s survey! We'd like to ask you a few questions." },
  "survey.noQuestions": { ja: "質問が設定されていません。", en: "No questions have been set up." },
  "survey.sessionFailed": { ja: "セッションの作成に失敗しました。", en: "Failed to create session." },
  "survey.thankYou": { ja: "ありがとうございました！", en: "Thank you!" },
  "survey.title": { ja: "アンケート", en: "Survey" },
  "survey.chars": { ja: "文字", en: "chars" },
  "survey.resultFetchFailed": { ja: "結果の取得に失敗しました", en: "Failed to fetch results" },

  // Result page
  "result.title": { ja: "クチコミ文章が完成しました！", en: "Your review is ready!" },
  "result.shopMessage": { ja: "ショップからのメッセージ", en: "Message from Shop" },
  "result.review": { ja: "クチコミ", en: "Review" },
  "result.copy": { ja: "コピーする", en: "Copy" },
  "result.copied": { ja: "コピーしました！", en: "Copied!" },
  "result.aiNote": { ja: "※ この口コミ文章はAIが生成したものです。内容を確認・編集してから投稿してください。", en: "* This review was generated by AI. Please review and edit before posting." },
  "result.coupon": { ja: "クーポン", en: "Coupon" },
  "result.couponExpiry": { ja: "有効期限:", en: "Valid until:" },
  "result.postGoogle": { ja: "Google Mapで口コミを投稿", en: "Post Review on Google Maps" },
  "result.backToSurvey": { ja: "アンケートへ戻る", en: "Back to Survey" },
};
